### ISSUE TITLE
Reusable snippets between reposeed and reposeed-server

### ISSUE THREAD

**Issue by stp-ip** [okkur/reposeed-server#1]
Currently reposeed has two implementations, which at least share the same config. Might be good to let one rely on the other. But open for discussion.

**Comment by erbesharat** [comment]
We can change reposeed's config to support JSON too and then use it in reposeed-server.

**Comment by erbesharat** [comment]
Added JSON support in okkur/reposeed#44 and used the reposeed's config package in 8f77a5b040abe107744a1cfae2fd026b2890f5aa

**Comment by stp-ip** [comment]
Merged and +1 for the approach.
