### ISSUE TITLE
Choose one repository to get template files and use them in both server and cli

### ISSUE THREAD

**Issue by stp-ip** [okkur/reposeed-server#2]
Probably best to let reposeed use packr to pack up the templates and reposeed-server just imports this.
Happy to discuss the pros and cons.

**Comment by erbesharat** [comment]
So I think we should generate templates.go file using ```packr``` command in the reposeed and add a method to get the box from the file and use it in both reposeed and reposeed-server. We also should add ```packr clean``` and ```packr``` commands in the reposeed's Makefile.

**Comment by stp-ip** [comment]
Sounds like a sane approach. That will already reduce the amount of duplication quite a bit and at the same time enhance the reposeed side of things.
