### ISSUE TITLE
Vendor current depencencies

### ISSUE THREAD

**Issue by stp-ip** [okkur/reposeed-server#4]
Currently no deps are vendored. Deps should be vendored to reduce the likelihood of lost packages.

**Comment by erbesharat** [comment]
Adding dependencies to the vendor folder would add something around 3k files. Are you sure about it?

**Comment by stp-ip** [comment]
Another approach would be to just use locking with dep or vgo.
Vendoring is also preventing loosing packages.
My personal preference is vendoring, but let's go with locking of the deps via dep or vgo, whatever you think is best. Might be great to play around with vgo.

**Comment by erbesharat** [comment]
I believe vendoring dependencies is important because something like go-bindata case maybe happens in future for other libraries too. So since we don't have something like npm to prevent these situations in go community, I think we should vendor all dependencies :)

**Comment by erbesharat** [comment]
vendored deps in 1f7ad0799c409e932bc64af6d3a2ffdcf6b8d669
