### ISSUE TITLE
Reconsider usage of iris

### ISSUE THREAD

**Issue by stp-ip** [okkur/reposeed-server#5]
Might be wise to switch from iris to something else. Gobuffalo or plain net/http?

Reason:
http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html?m=1

**Comment by erbesharat** [comment]
Wow! so I think we should choose another library 😄 will work on this issue when others got fixed.

**Comment by erbesharat** [comment]
All the issues got fixed and used gin instead of Iris.

**Comment by stp-ip** [comment]
You can open the specific PRs with master. Then I or Antoine can do a final review. Overall looks great. Looking forward to testing it out with the zip download. (long-term idea is a create PR with the changes support, but let's leave that for now).
